/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Challan {
  'id' : bigint,
  'status' : Status,
  'fineAmount' : bigint,
  'date' : string,
  'vehicleNumber' : string,
  'officerName' : string,
  'discountedAmount' : bigint,
  'location' : string,
  'violationType' : string,
}
export type Status = { 'pending' : null } |
  { 'paid' : null };
export interface _SERVICE {
  'addChallan' : ActorMethod<
    [string, string, bigint, string, string, string],
    bigint
  >,
  'getChallan' : ActorMethod<[bigint], Challan>,
  'getChallansByVehicle' : ActorMethod<[string], Array<Challan>>,
  'payChallan' : ActorMethod<[bigint], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];