/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null });
export const Challan = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'fineAmount' : IDL.Nat,
  'date' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'officerName' : IDL.Text,
  'discountedAmount' : IDL.Nat,
  'location' : IDL.Text,
  'violationType' : IDL.Text,
});
export const UtrStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UtrRecord = IDL.Record({
  'id' : IDL.Nat,
  'utr' : IDL.Text,
  'status' : UtrStatus,
  'challanId' : IDL.Nat,
  'vehicleNumber' : IDL.Text,
  'submittedAt' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addChallan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'approveUtr' : IDL.Func([IDL.Nat], [], []),
  'getChallan' : IDL.Func([IDL.Nat], [Challan], ['query']),
  'getChallansByVehicle' : IDL.Func([IDL.Text], [IDL.Vec(Challan)], ['query']),
  'getUpiId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUtrSubmissions' : IDL.Func([], [IDL.Vec(UtrRecord)], ['query']),
  'payChallan' : IDL.Func([IDL.Nat], [], []),
  'rejectUtr' : IDL.Func([IDL.Nat], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'setUpiId' : IDL.Func([IDL.Text], [], []),
  'submitUtr' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null });
  const Challan = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'fineAmount' : IDL.Nat,
    'date' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'officerName' : IDL.Text,
    'discountedAmount' : IDL.Nat,
    'location' : IDL.Text,
    'violationType' : IDL.Text,
  });
  const UtrStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UtrRecord = IDL.Record({
    'id' : IDL.Nat,
    'utr' : IDL.Text,
    'status' : UtrStatus,
    'challanId' : IDL.Nat,
    'vehicleNumber' : IDL.Text,
    'submittedAt' : IDL.Text,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addChallan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'approveUtr' : IDL.Func([IDL.Nat], [], []),
    'getChallan' : IDL.Func([IDL.Nat], [Challan], ['query']),
    'getChallansByVehicle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Challan)],
        ['query'],
      ),
    'getUpiId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUtrSubmissions' : IDL.Func([], [IDL.Vec(UtrRecord)], ['query']),
    'payChallan' : IDL.Func([IDL.Nat], [], []),
    'rejectUtr' : IDL.Func([IDL.Nat], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'setUpiId' : IDL.Func([IDL.Text], [], []),
    'submitUtr' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };