/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Challan {
  'id' : bigint,
  'status' : Status,
  'fineAmount' : bigint,
  'date' : string,
  'vehicleNumber' : string,
  'officerName' : string,
  'discountedAmount' : bigint,
  'location' : string,
  'violationType' : string,
}
export interface ManualPaymentRecord {
  'id' : bigint,
  'utr' : string,
  'status' : UtrStatus,
  'vehicleNumber' : string,
  'violations' : string,
  'submittedAt' : string,
  'totalAmount' : bigint,
  'phone' : string,
}
export type Status = { 'pending' : null } |
  { 'paid' : null };
export interface UtrRecord {
  'id' : bigint,
  'utr' : string,
  'status' : UtrStatus,
  'challanId' : bigint,
  'vehicleNumber' : string,
  'submittedAt' : string,
  'amount' : bigint,
}
export type UtrStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ViolationType {
  'id' : bigint,
  'name' : string,
  'amount' : bigint,
}
export interface _SERVICE {
  'addChallan' : ActorMethod<
    [string, string, bigint, string, string, string],
    bigint
  >,
  'addViolationType' : ActorMethod<[string, bigint], bigint>,
  'approveManualPayment' : ActorMethod<[bigint], undefined>,
  'approveUtr' : ActorMethod<[bigint], undefined>,
  'deleteViolationType' : ActorMethod<[bigint], undefined>,
  'getApiConfig' : ActorMethod<
    [],
    { 'apiKey' : [] | [string], 'apiBaseUrl' : [] | [string] }
  >,
  'getChallan' : ActorMethod<[bigint], Challan>,
  'getChallansByVehicle' : ActorMethod<[string], Array<Challan>>,
  'getManualPayments' : ActorMethod<[], Array<ManualPaymentRecord>>,
  'getSupportNumber' : ActorMethod<[], [] | [string]>,
  'getUpiId' : ActorMethod<[], [] | [string]>,
  'getUtrSubmissions' : ActorMethod<[], Array<UtrRecord>>,
  'getViolationTypes' : ActorMethod<[], Array<ViolationType>>,
  'payChallan' : ActorMethod<[bigint], undefined>,
  'rejectManualPayment' : ActorMethod<[bigint], undefined>,
  'rejectUtr' : ActorMethod<[bigint], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'setApiConfig' : ActorMethod<[string, string], undefined>,
  'setSupportNumber' : ActorMethod<[string], undefined>,
  'setUpiId' : ActorMethod<[string], undefined>,
  'submitManualPayment' : ActorMethod<
    [string, string, string, bigint, string, string],
    bigint
  >,
  'submitUtr' : ActorMethod<[bigint, string, bigint, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];