/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null });
export const Challan = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'fineAmount' : IDL.Nat,
  'date' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'officerName' : IDL.Text,
  'discountedAmount' : IDL.Nat,
  'location' : IDL.Text,
  'violationType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addChallan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getChallan' : IDL.Func([IDL.Nat], [Challan], ['query']),
  'getChallansByVehicle' : IDL.Func([IDL.Text], [IDL.Vec(Challan)], ['query']),
  'payChallan' : IDL.Func([IDL.Nat], [], []),
  'seedSampleData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null });
  const Challan = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'fineAmount' : IDL.Nat,
    'date' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'officerName' : IDL.Text,
    'discountedAmount' : IDL.Nat,
    'location' : IDL.Text,
    'violationType' : IDL.Text,
  });
  
  return IDL.Service({
    'addChallan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getChallan' : IDL.Func([IDL.Nat], [Challan], ['query']),
    'getChallansByVehicle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Challan)],
        ['query'],
      ),
    'payChallan' : IDL.Func([IDL.Nat], [], []),
    'seedSampleData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };